version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
    volumes:
      - dbvolume:/etc/mongo

  app:
    build: .
    container_name: "app"
    ports:
      - 8080:8080
    env_file:
      - ./server/.env

volumes:
  dbvolume:
